// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wixzqilqithhlybhyite.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeHpxaWxxaXRoaGx5Ymh5aXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjE2NTksImV4cCI6MjA3MTk5NzY1OX0.XnAj1YksRuxvUjC4oLDQSN0mx-ArJOH23JhjUC5vWUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});