version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ghostvault-db
    restart: always
    environment:
      POSTGRES_USER: flameadmin
      POSTGRES_PASSWORD: ghostfire
      POSTGRES_DB: ghostvault
    ports:
      - "5433:5432"
    volumes:
      - ./local-storage/database:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgrest:
    image: postgrest/postgrest
    container_name: ghostvault-api
    restart: always
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://flameadmin:ghostfire@db:5432/ghostvault
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: supersecretjwtkeythatisatleast32characters
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    container_name: ghostvault-storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ghostadmin
      MINIO_ROOT_PASSWORD: ghoststorage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./local-storage/minio:/data

  # hanko:
  #   image: teamhanko/hanko:0.20.1
  #   container_name: ghostvault-auth
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     HANKO_DATABASE_URL: postgres://flameadmin:ghostfire@db:5432/ghostvault
  #     HANKO_JWT_SECRET: supersecretjwt
  #   command: serve public

# Local storage now mapped to ./local-storage/ directory
# volumes:
#   db_data:
#   minio_data:
