
from pathlib import Path
from .indexer import list_projects

TEMPLATE = """# Project Sanctum Catalog

This catalog was generated by **Project Sanctum CLI**. It lists detected projects and key metadata.

| Project | Types | Root | First Seen | Last Scanned |
|---|---|---|---|---|
{rows}
"""

def generate_catalog(db_path: Path, out_path: Path):
    rows = []
    for (pid_name_idx, name, root, types, first_seen, last_scanned) in list_projects(db_path):
        types = types or "-"
        rows.append(f"| {name} | {types} | `{root}` | {first_seen} | {last_scanned} |")
    content = TEMPLATE.format(rows="\n".join(rows) if rows else "| _No projects indexed yet_ | - | - | - | - |")
    out_path.write_text(content)
    return out_path
